# @package _group_
data_root_dir: /scratch_net/schusch/roandres/Code/Inpainting/datasets/ImageNet
out_root_dir: /scratch_net/schusch/roandres/Code/Inpainting/baselines/lama/experiments/ImageNet
tb_dir: /scratch_net/schusch/roandres/Code/Inpainting/baselines/lama/tb_logs/ImageNet
pretrained_models: /scratch_net/schusch/roandres/Code/Inpainting/baselines/lama/checkpoints/ImageNet
