# @package _group_
data_root_dir: /scratch_net/schusch/roandres/Code/Inpainting/datasets/WikiArt
out_root_dir: /scratch_net/schusch/roandres/Code/Inpainting/baselines/lama/experiments/WikiArt
tb_dir: /scratch_net/schusch/roandres/Code/Inpainting/baselines/lama/tb_logs/WikiArt
pretrained_models: /scratch_net/schusch/roandres/Code/Inpainting/baselines/lama/checkpoints/WikiArt
